pipeline {
    agent any
    
    environment {
        PROJECT_DIR = 'messaging_app'
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                url: 'https://github.com/alx-backend-python.git',
                credentialsId: 'github-credentials'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir(PROJECT_DIR) {
                    // Explicit path to requirements.txt and using pip3
                    sh 'pip3 install -r messaging_app/requirements.txt'
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'pytest --junitxml=test-results.xml'
                }
            }
            post {
                always {
                    junit "${PROJECT_DIR}/test-results.xml"
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'docker build -t messaging-app:latest .'
                }
            }
        }
        
        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    dir(PROJECT_DIR) {
                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                        sh 'docker tag messaging-app:latest $DOCKER_USER/messaging-app:latest'
                        sh 'docker push $DOCKER_USER/messaging-app:latest'
                    }
                }
            }
        }
    }
}